### ISSUE TITLE
Restore --go option

### ISSUE THREAD

**Issue by ftassi** [ideatosrl/Idephix#61]
```
➜  Idephix git:(master) bin/idx --go
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'The "--go" option does not exist.' in /Users/ftassi/workspace/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php:213
Stack trace:
#0 /Users/ftassi/workspace/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php(154): Symfony\Component\Console\Input\ArgvInput->addLongOption('go', NULL)
#1 /Users/ftassi/workspace/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php(86): Symfony\Component\Console\Input\ArgvInput->parseLongOption('--go')
#2 /Users/ftassi/workspace/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/Input.php(61): Symfony\Component\Console\Input\ArgvInput->parse()
#3 /Users/ftassi/workspace/Idephix/src/Idephix/bootstrap.php(14): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#4 /Users/ftassi/workspace/Idephix/bin/idx(21): Idephix\run()
#5 {main}
  thrown in /Users/ftassi/workspace/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php on line 213

Fatal error: Uncaught exception 'RuntimeException' with message 'The "--go" option does not exist.' in /Users/ftassi/workspace/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php on line 213

RuntimeException: The "--go" option does not exist. in /Users/ftassi/workspace/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php on line 213

Call Stack:
    0.0016     236040   1. {main}() /Users/ftassi/workspace/Idephix/bin/idx:0
    0.0183     526168   2. Idephix\run() /Users/ftassi/workspace/Idephix/bin/idx:21
    0.0438    1840440   3. Symfony\Component\Console\Input\Input->bind() /Users/ftassi/workspace/Idephix/src/Idephix/bootstrap.php:14
    0.0438    1840168   4. Symfony\Component\Console\Input\ArgvInput->parse() /Users/ftassi/workspace/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/Input.php:61
    0.0439    1840528   5. Symfony\Component\Console\Input\ArgvInput->parseLongOption() /Users/ftassi/workspace/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php:86
    0.0439    1841096   6. Symfony\Component\Console\Input\ArgvInput->addLongOption() /Users/ftassi/workspace/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php:154```

**Comment by dymissy** [comment]
If you're using Idephix via Composer, a workaround while the bug will be fixed could be force the version to the following:

`"ideato/idephix": "0.0.1"`

**Comment by ftassi** [comment]
This seems to be solved now. If not, I'm just not able to replicate it, could someone provide a specific idxfile that shows the issue? 

/cc @dymissy @francescotrucchia @fain182 @ricfrank @micheleorselli

**Comment by fain182** [comment]
I have added some functional tests and it seems fixed..

**Comment by ftassi** [comment]
Ok, let's consider it closed then
